name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t keekenti/react-fib-test -f ./client/Dockerfile.dev .
      - run: docker run -e CI=true keekenti/react-fib-test npm test

      - run: docker build -t keekenti/react-fib-client ./client
      - run: docker build -t keekenti/react-fib-nginx ./nginx
      - run: docker build -t keekenti/react-fib-server ./server
      - run: docker build -t keekenti/react-fib-worker ./worker
 
      - run: docker push keekenti/react-fib-client
      - run: docker push keekenti/react-fib-nginx
      - run: docker push keekenti/react-fib-server
      - run: docker push keekenti/react-fib-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-app
          environment_name: Dockerreactapp-env
          existing_bucket_name: elasticbeanstalk-us-east-1-731241204927
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
